######################################
# Param\u00e8tres de connexion JDBC
######################################
# MYSQL / MariaDB  local : mysql-connector-java-8.0.18.jar
# XAMPP : MySQL écoute sur localhost:3306 par défaut
url=jdbc:mysql://localhost:3306/sirh?serverTimezone=UTC&useSSL=false
utilBD=sirh_util
mdpBD=secret

######################################
# Emplacement de l'image en arri\u00e8re plan des vues
######################################
imageDeFond=/ressources/StesioImageDeFond.jpg

