/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appli.vue;

/**
 *
 * @author minle
 */
public class JFrameGUIEmploye extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameGUIEmploye.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public JFrameGUIEmploye() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSupSalarie = new javax.swing.JButton();
        jButtonAjSalarie = new javax.swing.JButton();
        jButtonModifSalarie = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFicheSalarie = new javax.swing.JTable();
        jLabelStaticSalarie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSupSalarie.setText("Supprimer Salarié");
        jButtonSupSalarie.addActionListener(this::jButtonSupSalarieActionPerformed);

        jButtonAjSalarie.setText("Ajouter Salarié");
        jButtonAjSalarie.addActionListener(this::jButtonAjSalarieActionPerformed);

        jButtonModifSalarie.setText("Modifier Salarié");
        jButtonModifSalarie.addActionListener(this::jButtonModifSalarieActionPerformed);

        jTableFicheSalarie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Code", null},
                {"Nom", null},
                {"Prenom", null},
                {"Date naiss.", null},
                {"Date emb.", null},
                {"Fonction", null}
            },
            new String [] {
                "Propriété", "Valeur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFicheSalarie.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(jTableFicheSalarie);
        if (jTableFicheSalarie.getColumnModel().getColumnCount() > 0) {
            jTableFicheSalarie.getColumnModel().getColumn(0).setResizable(false);
            jTableFicheSalarie.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jLabelStaticSalarie.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelStaticSalarie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStaticSalarie.setText("Salarié");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAjSalarie, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonModifSalarie, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSupSalarie))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabelStaticSalarie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStaticSalarie, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjSalarie)
                    .addComponent(jButtonModifSalarie)
                    .addComponent(jButtonSupSalarie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSupSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupSalarieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSupSalarieActionPerformed

    private void jButtonAjSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjSalarieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjSalarieActionPerformed

    private void jButtonModifSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifSalarieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifSalarieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameGUIEmploye().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjSalarie;
    private javax.swing.JButton jButtonModifSalarie;
    private javax.swing.JButton jButtonSupSalarie;
    private javax.swing.JLabel jLabelStaticSalarie;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFicheSalarie;
    // End of variables declaration//GEN-END:variables
}
