/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appli.vue;

/**
 *
 * @author elven
 */
public class JFrameAjouter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameAjouter.class.getName());

    /**
     * Creates new form JFrameAjouter
     */
    public JFrameAjouter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodeAjouter = new javax.swing.JLabel();
        jLabelNomAjouter = new javax.swing.JLabel();
        jLabelPrenomAjouter = new javax.swing.JLabel();
        jLabelDateNaisAjouter = new javax.swing.JLabel();
        jLabelDateEmbaucheAjouter = new javax.swing.JLabel();
        jLabelFonctionAjouter = new javax.swing.JLabel();
        jLabelTauxHoraireAjouter = new javax.swing.JLabel();
        jLabelFamilleAjouter = new javax.swing.JLabel();
        jLabelNbEnfantAjouter = new javax.swing.JLabel();
        jLabelServiceAjouter = new javax.swing.JLabel();
        jLabelCategorieAjouter = new javax.swing.JLabel();
        jTextFieldCodeAjouter = new javax.swing.JTextField();
        jTextFieldNomAjouter = new javax.swing.JTextField();
        jTextFieldPrenomAjouter = new javax.swing.JTextField();
        jTextFieldDateNaissAjouter = new javax.swing.JTextField();
        jTextFieldDateEmbaucheAjouter = new javax.swing.JTextField();
        jTextFieldFonctionAjouter = new javax.swing.JTextField();
        jTextFieldTauxHoraireAjouter = new javax.swing.JTextField();
        jTextFieldFamilleAjouter = new javax.swing.JTextField();
        jTextFieldNbEnfantAjouter = new javax.swing.JTextField();
        jTextFieldServiceAjouter = new javax.swing.JTextField();
        jTextFieldCategorieAjouter = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jButtonRetourAjouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter_utilisateur");

        jLabelCodeAjouter.setText("Code :");

        jLabelNomAjouter.setText("Nom :");

        jLabelPrenomAjouter.setText("Prenom :");

        jLabelDateNaisAjouter.setText("Date Naissance :");

        jLabelDateEmbaucheAjouter.setText("Date Embauche :");

        jLabelFonctionAjouter.setText("Fonction :");

        jLabelTauxHoraireAjouter.setText("Taux Horaire :");

        jLabelFamilleAjouter.setText("Situation Familiale :");

        jLabelNbEnfantAjouter.setText("Nb Enfants :");

        jLabelServiceAjouter.setText("Service :");

        jLabelCategorieAjouter.setText("Categorie :");

        jTextFieldCategorieAjouter.addActionListener(this::jTextFieldCategorieAjouterActionPerformed);

        jButtonAjouter.setText("Ajouter");

        jButtonRetourAjouter.setText("Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFamilleAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldFamilleAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTauxHoraireAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTauxHoraireAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFonctionAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldFonctionAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCodeAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCodeAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelDateEmbaucheAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDateEmbaucheAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNbEnfantAjouter)
                            .addComponent(jLabelServiceAjouter)
                            .addComponent(jLabelCategorieAjouter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldServiceAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(jTextFieldNbEnfantAjouter)
                            .addComponent(jTextFieldCategorieAjouter)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAjouter)
                                .addGap(77, 77, 77)
                                .addComponent(jButtonRetourAjouter))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDateNaisAjouter)
                                .addGap(167, 167, 167)
                                .addComponent(jTextFieldDateNaissAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNomAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNomAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPrenomAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrenomAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCodeAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodeAjouter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomAjouter)
                    .addComponent(jTextFieldNomAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenomAjouter)
                    .addComponent(jTextFieldPrenomAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateNaisAjouter)
                    .addComponent(jTextFieldDateNaissAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateEmbaucheAjouter)
                    .addComponent(jTextFieldDateEmbaucheAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFonctionAjouter)
                    .addComponent(jTextFieldFonctionAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTauxHoraireAjouter)
                    .addComponent(jTextFieldTauxHoraireAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFamilleAjouter)
                    .addComponent(jTextFieldFamilleAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbEnfantAjouter)
                    .addComponent(jTextFieldNbEnfantAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelServiceAjouter)
                    .addComponent(jTextFieldServiceAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategorieAjouter)
                    .addComponent(jTextFieldCategorieAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRetourAjouter)
                    .addComponent(jButtonAjouter))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCategorieAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategorieAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCategorieAjouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameAjouter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonRetourAjouter;
    private javax.swing.JLabel jLabelCategorieAjouter;
    private javax.swing.JLabel jLabelCodeAjouter;
    private javax.swing.JLabel jLabelDateEmbaucheAjouter;
    private javax.swing.JLabel jLabelDateNaisAjouter;
    private javax.swing.JLabel jLabelFamilleAjouter;
    private javax.swing.JLabel jLabelFonctionAjouter;
    private javax.swing.JLabel jLabelNbEnfantAjouter;
    private javax.swing.JLabel jLabelNomAjouter;
    private javax.swing.JLabel jLabelPrenomAjouter;
    private javax.swing.JLabel jLabelServiceAjouter;
    private javax.swing.JLabel jLabelTauxHoraireAjouter;
    private javax.swing.JTextField jTextFieldCategorieAjouter;
    private javax.swing.JTextField jTextFieldCodeAjouter;
    private javax.swing.JTextField jTextFieldDateEmbaucheAjouter;
    private javax.swing.JTextField jTextFieldDateNaissAjouter;
    private javax.swing.JTextField jTextFieldFamilleAjouter;
    private javax.swing.JTextField jTextFieldFonctionAjouter;
    private javax.swing.JTextField jTextFieldNbEnfantAjouter;
    private javax.swing.JTextField jTextFieldNomAjouter;
    private javax.swing.JTextField jTextFieldPrenomAjouter;
    private javax.swing.JTextField jTextFieldServiceAjouter;
    private javax.swing.JTextField jTextFieldTauxHoraireAjouter;
    // End of variables declaration//GEN-END:variables
}
