/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appli.vue;

/**
 *
 * @author elven
 */
public class JFrameProfil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameProfil.class.getName());

    /**
     * Creates new form JFrameAjouter
     */
    public JFrameProfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodeProfil = new javax.swing.JLabel();
        jLabelNomProfil = new javax.swing.JLabel();
        jLabelPrenomProfil = new javax.swing.JLabel();
        jLabelDateNaisProfil = new javax.swing.JLabel();
        jLabelDateEmbaucheProfil = new javax.swing.JLabel();
        jLabelFonctionProfil = new javax.swing.JLabel();
        jLabelTauxHoraireProfil = new javax.swing.JLabel();
        jLabelFamilleProfil = new javax.swing.JLabel();
        jLabelNbEnfantProfil = new javax.swing.JLabel();
        jLabelServiceProfil = new javax.swing.JLabel();
        jLabelCategorieProfil = new javax.swing.JLabel();
        jTextFieldCodeProfil = new javax.swing.JTextField();
        jTextFieldNomProfil = new javax.swing.JTextField();
        jTextFieldPrenomProfil = new javax.swing.JTextField();
        jTextFieldDateNaissProfil = new javax.swing.JTextField();
        jTextFieldDateEmbaucheProfil = new javax.swing.JTextField();
        jTextFieldFonctionProfil = new javax.swing.JTextField();
        jTextFieldTauxHoraireProfil = new javax.swing.JTextField();
        jTextFieldFamilleProfil = new javax.swing.JTextField();
        jTextFieldNbEnfantProfil = new javax.swing.JTextField();
        jTextFieldServiceProfil = new javax.swing.JTextField();
        jTextFieldCategorieProfil = new javax.swing.JTextField();
        jButtonRetourProfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profil_utilisateur");

        jLabelCodeProfil.setText("Code :");

        jLabelNomProfil.setText("Nom :");

        jLabelPrenomProfil.setText("Prenom :");

        jLabelDateNaisProfil.setText("Date Naissance :");

        jLabelDateEmbaucheProfil.setText("Date Embauche :");

        jLabelFonctionProfil.setText("Fonction :");

        jLabelTauxHoraireProfil.setText("Taux Horaire :");

        jLabelFamilleProfil.setText("Situation Familiale :");

        jLabelNbEnfantProfil.setText("Nb Enfants :");

        jLabelServiceProfil.setText("Service :");

        jLabelCategorieProfil.setText("Categorie :");

        jTextFieldCodeProfil.setEditable(false);

        jTextFieldNomProfil.setEditable(false);

        jTextFieldPrenomProfil.setEditable(false);

        jTextFieldDateNaissProfil.setEditable(false);

        jTextFieldDateEmbaucheProfil.setEditable(false);

        jTextFieldFonctionProfil.setEditable(false);

        jTextFieldTauxHoraireProfil.setEditable(false);

        jTextFieldFamilleProfil.setEditable(false);

        jTextFieldNbEnfantProfil.setEditable(false);

        jTextFieldServiceProfil.setEditable(false);

        jTextFieldCategorieProfil.setEditable(false);
        jTextFieldCategorieProfil.addActionListener(this::jTextFieldCategorieProfilActionPerformed);

        jButtonRetourProfil.setText("Retour");
        jButtonRetourProfil.addActionListener(this::jButtonRetourProfilActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFamilleProfil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldFamilleProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTauxHoraireProfil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldTauxHoraireProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFonctionProfil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldFonctionProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelDateEmbaucheProfil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldDateEmbaucheProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNbEnfantProfil)
                                    .addComponent(jLabelServiceProfil)
                                    .addComponent(jLabelCategorieProfil))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldServiceProfil, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNbEnfantProfil)
                                    .addComponent(jTextFieldCategorieProfil)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDateNaisProfil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldDateNaissProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNomProfil)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNomProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabelPrenomProfil)
                                        .addGap(26, 26, 26)
                                        .addComponent(jTextFieldPrenomProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCodeProfil)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCodeProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jButtonRetourProfil)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomProfil)
                    .addComponent(jTextFieldNomProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenomProfil)
                    .addComponent(jTextFieldPrenomProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodeProfil)
                    .addComponent(jTextFieldCodeProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateNaisProfil)
                    .addComponent(jTextFieldDateNaissProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateEmbaucheProfil)
                    .addComponent(jTextFieldDateEmbaucheProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFonctionProfil)
                    .addComponent(jTextFieldFonctionProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTauxHoraireProfil)
                    .addComponent(jTextFieldTauxHoraireProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFamilleProfil)
                    .addComponent(jTextFieldFamilleProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbEnfantProfil)
                    .addComponent(jTextFieldNbEnfantProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelServiceProfil)
                    .addComponent(jTextFieldServiceProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategorieProfil)
                    .addComponent(jTextFieldCategorieProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRetourProfil)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCategorieProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategorieProfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCategorieProfilActionPerformed

    private void jButtonRetourProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourProfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRetourProfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameProfil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetourProfil;
    private javax.swing.JLabel jLabelCategorieProfil;
    private javax.swing.JLabel jLabelCodeProfil;
    private javax.swing.JLabel jLabelDateEmbaucheProfil;
    private javax.swing.JLabel jLabelDateNaisProfil;
    private javax.swing.JLabel jLabelFamilleProfil;
    private javax.swing.JLabel jLabelFonctionProfil;
    private javax.swing.JLabel jLabelNbEnfantProfil;
    private javax.swing.JLabel jLabelNomProfil;
    private javax.swing.JLabel jLabelPrenomProfil;
    private javax.swing.JLabel jLabelServiceProfil;
    private javax.swing.JLabel jLabelTauxHoraireProfil;
    private javax.swing.JTextField jTextFieldCategorieProfil;
    private javax.swing.JTextField jTextFieldCodeProfil;
    private javax.swing.JTextField jTextFieldDateEmbaucheProfil;
    private javax.swing.JTextField jTextFieldDateNaissProfil;
    private javax.swing.JTextField jTextFieldFamilleProfil;
    private javax.swing.JTextField jTextFieldFonctionProfil;
    private javax.swing.JTextField jTextFieldNbEnfantProfil;
    private javax.swing.JTextField jTextFieldNomProfil;
    private javax.swing.JTextField jTextFieldPrenomProfil;
    private javax.swing.JTextField jTextFieldServiceProfil;
    private javax.swing.JTextField jTextFieldTauxHoraireProfil;
    // End of variables declaration//GEN-END:variables
}
