/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appli.vue;

/**
 *
 * @author elven
 */
public class JFrameModifier extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameModifier.class.getName());

    /**
     * Creates new form JFrameAjouter
     */
    public JFrameModifier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodeModifier = new javax.swing.JLabel();
        jLabelNomModifier = new javax.swing.JLabel();
        jLabelPrenomModifier = new javax.swing.JLabel();
        jLabelDateNaisModifier = new javax.swing.JLabel();
        jLabelDateEmbaucheModifier = new javax.swing.JLabel();
        jLabelFonctionModifier = new javax.swing.JLabel();
        jLabelTauxHoraireModifier = new javax.swing.JLabel();
        jLabelFamilleModifier = new javax.swing.JLabel();
        jLabelNbEnfantModifier = new javax.swing.JLabel();
        jLabelServiceModifier = new javax.swing.JLabel();
        jLabelCategorieModifier = new javax.swing.JLabel();
        jTextFieldCodeModifier = new javax.swing.JTextField();
        jTextFieldNomModifier = new javax.swing.JTextField();
        jTextFieldPrenomModifier = new javax.swing.JTextField();
        jTextFieldDateNaissModifier = new javax.swing.JTextField();
        jTextFieldDateEmbaucheModifier = new javax.swing.JTextField();
        jTextFieldFonctionModifier = new javax.swing.JTextField();
        jTextFieldTauxHoraireModifier = new javax.swing.JTextField();
        jTextFieldFamilleModifier = new javax.swing.JTextField();
        jTextFieldNbEnfantModifier = new javax.swing.JTextField();
        jTextFieldServiceModifier = new javax.swing.JTextField();
        jTextFieldCategorieModifier = new javax.swing.JTextField();
        jButtonModifier = new javax.swing.JButton();
        jButtonRetourModifier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modifier_utilisateur");

        jLabelCodeModifier.setText("Code :");

        jLabelNomModifier.setText("Nom :");

        jLabelPrenomModifier.setText("Prenom :");

        jLabelDateNaisModifier.setText("Date Naissance :");

        jLabelDateEmbaucheModifier.setText("Date Embauche :");

        jLabelFonctionModifier.setText("Fonction :");

        jLabelTauxHoraireModifier.setText("Taux Horaire :");

        jLabelFamilleModifier.setText("Situation Familiale :");

        jLabelNbEnfantModifier.setText("Nb Enfants :");

        jLabelServiceModifier.setText("Service :");

        jLabelCategorieModifier.setText("Categorie :");

        jTextFieldCategorieModifier.addActionListener(this::jTextFieldCategorieModifierActionPerformed);

        jButtonModifier.setText("Modifier");

        jButtonRetourModifier.setText("Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFamilleModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldFamilleModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTauxHoraireModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTauxHoraireModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFonctionModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldFonctionModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCodeModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCodeModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelDateEmbaucheModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDateEmbaucheModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNbEnfantModifier)
                            .addComponent(jLabelServiceModifier)
                            .addComponent(jLabelCategorieModifier))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldServiceModifier, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(jTextFieldNbEnfantModifier)
                            .addComponent(jTextFieldCategorieModifier)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelNomModifier)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNomModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelPrenomModifier)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrenomModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonModifier)
                                    .addGap(60, 60, 60)
                                    .addComponent(jButtonRetourModifier))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelDateNaisModifier)
                                    .addGap(167, 167, 167)
                                    .addComponent(jTextFieldDateNaissModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodeModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodeModifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomModifier)
                    .addComponent(jTextFieldNomModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenomModifier)
                    .addComponent(jTextFieldPrenomModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateNaisModifier)
                    .addComponent(jTextFieldDateNaissModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateEmbaucheModifier)
                    .addComponent(jTextFieldDateEmbaucheModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFonctionModifier)
                    .addComponent(jTextFieldFonctionModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTauxHoraireModifier)
                    .addComponent(jTextFieldTauxHoraireModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFamilleModifier)
                    .addComponent(jTextFieldFamilleModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbEnfantModifier)
                    .addComponent(jTextFieldNbEnfantModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelServiceModifier)
                    .addComponent(jTextFieldServiceModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategorieModifier)
                    .addComponent(jTextFieldCategorieModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonRetourModifier))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCategorieModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategorieModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCategorieModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameModifier().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRetourModifier;
    private javax.swing.JLabel jLabelCategorieModifier;
    private javax.swing.JLabel jLabelCodeModifier;
    private javax.swing.JLabel jLabelDateEmbaucheModifier;
    private javax.swing.JLabel jLabelDateNaisModifier;
    private javax.swing.JLabel jLabelFamilleModifier;
    private javax.swing.JLabel jLabelFonctionModifier;
    private javax.swing.JLabel jLabelNbEnfantModifier;
    private javax.swing.JLabel jLabelNomModifier;
    private javax.swing.JLabel jLabelPrenomModifier;
    private javax.swing.JLabel jLabelServiceModifier;
    private javax.swing.JLabel jLabelTauxHoraireModifier;
    private javax.swing.JTextField jTextFieldCategorieModifier;
    private javax.swing.JTextField jTextFieldCodeModifier;
    private javax.swing.JTextField jTextFieldDateEmbaucheModifier;
    private javax.swing.JTextField jTextFieldDateNaissModifier;
    private javax.swing.JTextField jTextFieldFamilleModifier;
    private javax.swing.JTextField jTextFieldFonctionModifier;
    private javax.swing.JTextField jTextFieldNbEnfantModifier;
    private javax.swing.JTextField jTextFieldNomModifier;
    private javax.swing.JTextField jTextFieldPrenomModifier;
    private javax.swing.JTextField jTextFieldServiceModifier;
    private javax.swing.JTextField jTextFieldTauxHoraireModifier;
    // End of variables declaration//GEN-END:variables
}
